config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  namespace :api, defaults: {format: :json} do

    resources :events, only: [:create]
  end
  

  resources :registered_applications
  resources :events



  get 'welcome/index'
  get 'welcome/about'

  
  root to: 'welcome#index'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                        :integer          not null, primary key
#  name                      :string
#  registered_application_id :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#

class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
# == Schema Information
#
# Table name: registered_applications
#
#  id          :integer          not null, primary key
#  name        :string
#  url         :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

  default_scope {order('created_at DESC')}
  scope :visible_to, -> (user){user.admin? ? all : where(user: user) }

  validates :name, length: {minimum: 2}, presence: true
  validates :description, length: {minimum: 10}, presence: true
  validates :user, presence: true
  validates_uniqueness_of :url

end 

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime
#  updated_at             :datetime
#  role                   :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications, dependent: :destroy

  def admin?
    role == 'admin'
  end

  def moderator?
    role == 'moderator'
  end


end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  
  skip_before_action :verify_authenticity_token
  after_action :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def index
    @events = Event.all
    render json: @events, status: :ok
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    render json: @event
  end

  def edit
  end

  def create

    @registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if @registered_application

      @event = @registered_application.events.build(event_params)
      if @event.save
        render json: @event, status: :created
      else
        render @event.errors, status: :unprocessable_entity
      end
    
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
  end


  def event_params
    params.require(:event).permit(:name)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
   redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  
  def index   
    @registered_applications = RegisteredApplication.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @registered_applications
  end

  def new
    @registered_application = RegisteredApplication.new
    authorize @registered_application
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    authorize @registered_application
    @event_groupings = @registered_application.events.group_by(&:name)
    # @event = @registered_application.events
    # @count = @event.inject(Hash.new(0)) {|h,e| h[e] += 1; h}
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
    authorize @registered_application
  end

  def create
    @registered_application = current_user.registered_applications.build(registered_application_params)
    authorize @registered_application
    if @registered_application.save
      redirect_to @registered_application, notice: "Application was registered successfully."
    else
      flash[:error] = "Error registering application. Please try again."
      render :new
    end
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    authorize @registered_application
    if @registered_application.update_attributes(registered_application_params)
      redirect_to @registered_application
    else
      flash[:error] = "Error updating registered application. Please try again."
      render :edit
    end
  end


  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    name = @registered_application.name

    authorize @registered_application
    if @registered_application.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to registered_applications_path
    else
      flash[:error] = "Error deleting application. Please try again."
      render :show
    end
  end


  def registered_application_params
    params.require(:registered_application).permit(:name, :url, :description)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def my_name
    "Shu Haur Tang"
  end

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <meta name= "viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class ="container">
  <ul class = 'nav nav-tabs'> 
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Applications", registered_applications_path %></li>
        <div class = "pull-right user-info">
          <% if current_user %>
            Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>

        <% if flash[:notice] %>
          <div class = "alert alert-success">
            <button type ="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error]%>
          <div class = "alert alert-danger">
            <button type ="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class = "alert alert-warning">
            <button type ="button" class="close" data-dismiss="alert">&times;</button>
          </div>
        <% end %>
  </ul>
  <%= yield %>
</div>

</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for [registered_application] do |f| %>
  
  <% if registered_application.errors.any? %>
    <div class = "alert alert-danger">
      <h4>There are <%= pluralize(registered_application.errors.count, "error") %>.</h4>
      <ul>
        <% registered_application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div> 
  <% end %> 

  <%= form_group_tag(registered_application.errors[:title]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter name of the application" %>
  <% end %>
  <%= form_group_tag(registered_application.errors[:url]) do %>
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter the URL of the application" %>
  <% end %>
  <%= form_group_tag(registered_application.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: "Briefly describe the application here" %>
  <% end %>
  <div class = "form-group">
    <%= f.submit "Save", class: 'btn btn-success'%>
  </div>
<% end %>

app/views/registered_applications/edit.html.erb
<h1>Edit Application</h1>

<div class = "row">
  <div class = "col-md-4">
      <p>Guidelines for new application:</p>
      <dl>
        <dt>Make sure application works</dt>
        <dd>The tool won't work if your app is broken!</dd>
        <dt>Appropriate application</dt>
        <dd>Any member registering an app with virus will immediately be removed from the community</dd>
      </dl>
  </div>

  <div class = "col-md-8">
    <%= render partial: 'form', locals: {registered_application: @registered_application} %>
  </div>

</div>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h1>

<div class = "row">
  <div class = "col-md-8">
    <% @registered_applications.each do |app| %>
      <div class = "media">
        <div class = "media-body">
          <h4 class = "media-heading">
            <%= link_to app.name, app %> <small><%= link_to app.url %></small>
          </h4>
            <small>
              submitted <%= time_ago_in_words(app.created_at) %> by <%= app.user.name %>
            </small>
            <%= markdown_to_html app.description%>
        </div>
      </div>
    <% end %>
    <%= will_paginate @registered_applications %>
  </div>
  <div class = "col-md-4">
    <% if policy(RegisteredApplication.new).create? %>
      <%= link_to "Register New Application", new_registered_application_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<h1>Register a new application!</h1>

<div class = "row">
  <div class = "col-md-4">
    <p>Guidelines for new application:</p>
      <dl>
        <dt>Make sure application works</dt>
        <dd>The tool won't work if your app is broken!</dd>
        <dt>Appropriate application</dt>
        <dd>Any member registering an app with virus will immediately be removed from the community</dd>
      </dl>
  </div>

  <div class = "col-md-8">
    <%= render partial: 'form', locals: {registered_application: @registered_application} %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>
<h4>URL: <%= link_to @registered_application.url %></h4>

<div class = "row">
  <div class = "col-md-8">
    <p><%= markdown_to_html @registered_application.description%></p>
    <%= pie_chart @registered_application.events.group(:name).count %>
    <% @event_groupings.each do |event_group| %>
      <small>
        <% event_grouped_name = event_group[0]%>
        <% events = event_group[1] %>
        <p>Event <%= event_grouped_name %> count: <%= events.count %></p>
          <% events.each do |e| %>
            <p><%= e.name %> <%= e.created_at %></p>
          <% end %>
      </small>
    <% end %>
  </div>

  <div class = "col-md-4">
    <% if policy(@registered_application).update? %>
      <%= link_to "Edit Application", edit_registered_application_path, class: 'btn btn-success'%>  
    <% end %>
    <% if policy(@registered_application).destroy?%>
      <%= link_to "Delete Application", @registered_application, method: :delete, class:' btn btn-danger', data: {confirm: 'Are you sure you want to delete this application?'} %>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Blocmetrics</h1>
<p>Created by: <%= my_name %></p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron" id ="front-page">
  <h1>Blocmetrics</h1>
  <p>Blocmetrics is a tracking and reporting tool</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-sm' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-sm'%> today!
  </p>
</div>

<div class="row">
</div>